class ApartmentModel {
  final String name;
  final String price;
  final String location;
  final double review;
  final String telephone;
  final String desc;
  final int threeinRoom;
  final int twoinRoom;
  final int oneinRoom;
  final List<String> features;
  final List<String> personImages;
  final List<String> images;

  ApartmentModel({
    this.name,
    this.price,
    this.location,
    this.review,
    this.telephone,
    this.desc,
    this.threeinRoom,
    this.twoinRoom,
    this.oneinRoom,
    this.features,
    this.personImages,
    this.images,
  });

  static List<ApartmentModel> list = [
    ApartmentModel(
      name: "SSNIT Hostel",
      price: '2985',
      location: "UPSHS Road",
      telephone: '',
      desc:
      "Four-in-a-room is available for 1750 cedis, it is located on UPSHS road",
      threeinRoom: 2325,
      twoinRoom: 2985,
      oneinRoom: 4910,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["ssnit", "ssnit1", "ssnit2"],
    ),
    ApartmentModel(
      name: "Oye Inn Abodan",
      price: '3500',
      location: "Science",
      telephone: '0571407500',
      desc:
      "Located in Science, Just minutes from College of Agriculture and Natural Science. Centrally located at Amamoma field",
      threeinRoom: 0,
      twoinRoom: 3500,
      oneinRoom: 6000,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["oye", "oye1", "oye"],
    ),
    ApartmentModel(
      name: "Nest Hostel",
      price: '2000',
      location: "Kwaprow",
      telephone: '',
      desc: "Located around sandwich lecture theatre",
      threeinRoom: 0,
      twoinRoom: 2000,
      oneinRoom: 4000,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["Nest", "Nest", "Nest"],
    ),
    ApartmentModel(
      name: "Adjoa Dufie Palace",
      price: 'Unknown',
      location: "Ayensu",
      telephone: '',
      desc: "located in Ayensu township",
      threeinRoom: 0,
      twoinRoom: 0,
      oneinRoom: 0,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["adjoa", "adjoa", "adjoa"],
    ),
    ApartmentModel(
      name: "Kent Villa",
      price: 'Unknown',
      location: "Ayensu" ,
      telephone: '',
      desc: "located in Ayensu township",
      threeinRoom: 0,
      twoinRoom: 0,
      oneinRoom: 0,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["kent", "kent", "kent"],
    ),
    ApartmentModel(
      name: "Shirley Addo-Nkrumah Hostel",
      price: 'Unknown',
      location: "Amamoma-Round Palace",
      telephone: '',
      desc: "located in Amamoma township",
      threeinRoom: 0,
      twoinRoom: 0,
      oneinRoom: 0,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["shirley", "shirley", "shirley"],
    ),
    ApartmentModel(
      name: "Round Palace",
      price: 'Unknown',
      location: "Amamoma-Round Palace",
      telephone: '',
      desc: "located in Amamoma township",
      threeinRoom: 0,
      twoinRoom: 0,
      oneinRoom: 0,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["round_palace", "round_palace", "round_palace"],
    ),
    ApartmentModel(
      name: "A&G Hostel",
      price: 'Unknown',
      location: "Amamoma-Round Palace",
      telephone: '',
      desc: "located in Amamoma township",
      threeinRoom: 0,
      twoinRoom: 0,
      oneinRoom: 0,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["AandG", "AandG", "AandG"],
    ),
    ApartmentModel(
      name: "Egyapa Residence",
      price: 'Unknown',
      location: "Amamoma-Round Palace",
      telephone: '',
      desc: "located in Amamoma township",
      threeinRoom: 0,
      twoinRoom: 0,
      oneinRoom: 0,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["Egyapa", "Egyapa", "Egyapa"],
    ),
    ApartmentModel(
      name: "Zion Hostel",
      price: 'Unknown',
      location: "Amamoma-Round Palace",
      telephone: '',
      desc: "located in Amamoma township",
      threeinRoom: 0,
      twoinRoom: 0,
      oneinRoom: 0,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["zion", "zion", "zion"],
    ),
    ApartmentModel(
      name: "Emmanuels House",
      price: 'Unknown',
      location: "Amamoma-Round Palace",
      telephone: '',
      desc: "located in Amamoma township",
      threeinRoom: 0,
      twoinRoom: 0,
      oneinRoom: 0,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["emmanuels", "emmanuels", "emmanuels"],
    ),
    ApartmentModel(
      name: "Koba Hostel",
      price: 'Unknown',
      location: "Amamoma-Round Palace",
      telephone: '',
      desc: "located in Amamoma township",
      threeinRoom: 0,
      twoinRoom: 0,
      oneinRoom: 0,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["Koba", "Koba", "Koba"],
    ),
    ApartmentModel(
      name: "Joeh's Court",
      price: 'Unknown',
      location: "Amamoma-Round Palace",
      telephone: '',
      desc: "located in Amamoma township",
      threeinRoom: 0,
      twoinRoom: 0,
      oneinRoom: 0,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["joeh", "joeh", "joeh"],
    ),
    ApartmentModel(
      name: "JKF Hostel",
      price: 'Unknown',
      location: "Amamoma-Round Palace",
      telephone: '',
      desc: "located in Amamoma township",
      threeinRoom: 0,
      twoinRoom: 0,
      oneinRoom: 0,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["jfk", "jfk", "jfk"],
    ),
    ApartmentModel(
      name: "Green Hostel",
      price: 'Unknown',
      location: "Amamoma-Round Palace",
      telephone: '',
      desc: "located in Amamoma township",
      threeinRoom: 0,
      twoinRoom: 0,
      oneinRoom: 0,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["green", "green", "green"],
    ),
    ApartmentModel(
      name: "Gafa Inn",
      price: 'Unknown',
      location: "Amamoma-Round Palace",
      telephone: '',
      desc: "located in Amamoma township",
      threeinRoom: 0,
      twoinRoom: 0,
      oneinRoom: 0,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["Gafa Inn", "Gafa Inn", "Gafa Inn"],
    ),
    ApartmentModel(
      name: "Commander Hostel",
      price: 'Unknown',
      location: "Amamoma-Round Palace",
      telephone: '',
      desc: "located in Amamoma township",
      threeinRoom: 0,
      twoinRoom: 0,
      oneinRoom: 0,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["commander", "commander", "commander"],
    ),
    ApartmentModel(
      name: "Grace Hostel",
      price: 'Unknown',
      location: "Amamoma",
      telephone: '',
      desc: "located in Amamoma township",
      threeinRoom: 0,
      twoinRoom: 0,
      oneinRoom: 0,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["Grace Hostel", "Grace Hostel", "Grace Hostel"],
    ),
    ApartmentModel(
      name: "Sterner Hostel",
      price: 'Unknown',
      location: "Amamoma",
      telephone: '',
      desc: "located in Amamoma township",
      threeinRoom: 0,
      twoinRoom: 0,
      oneinRoom: 0,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["sterner", "sterner1", "sterner2"],
    ),
    ApartmentModel(
      name: "Empire",
      price: '2000',
      location: "Kwaprow",
      telephone: '0274447205',
      desc: "Located around sandwich lecture theatre",
      threeinRoom: 0,
      twoinRoom: 2000,
      oneinRoom: 4000,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["empire", "empire1", "empire2"],
    ),
    ApartmentModel(
      name: "Executive Hostel",
      price: '2750',
      location: "Old School road",
      telephone: '',
      desc: "located on old-school road right after jodok hostel",
      threeinRoom: 0508511685,
      twoinRoom: 2750,
      oneinRoom: 5510,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["executive", "exe1", "exe2"],
    ),
    ApartmentModel(
      name: "Sasakawa",
      price: '1200',
      location: "Sasakawa Restaurant",
      telephone: '',
      desc: "Around valco trust",
      threeinRoom: 1200,
      twoinRoom: 2400,
      oneinRoom: 3600,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["sasakawa", "sasakawa1", "sasakawa2"],
    ),
    ApartmentModel(
      name: "Ananse Web",
      price: '2500',
      location: "Kwaprow",
      telephone: '0243567820',
      desc: "Located around sandwich lecture theatre",
      threeinRoom: 0,
      twoinRoom: 2500,
      oneinRoom: 5000,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["web", "web1", "web2"],
    ),
    ApartmentModel(
      name: "Russian Lodge",
      price: '2500',
      location: "Kwaprow",
      telephone: '0242702072',
      desc: "Located around sandwich lecture theatre",
      threeinRoom: 0,
      twoinRoom: 2500,
      oneinRoom: 5000,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["rlodge", "rlodge1", "rlodge3"],
    ),
    ApartmentModel(
      name: "The Step Hostel",
      price: '1800',
      location: "Kwaprow",
      telephone: '',
      desc: "Located around sandwich lecture theatre",
      threeinRoom: 0,
      twoinRoom: 1800,
      oneinRoom: 3500,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["step", "step", "step"],
    ),
    ApartmentModel(
      name: "N/A",
      price: '1200',
      location: "Kwaprow",
      telephone: '0560227258',
      desc: "Located around sandwich lecture theatre",
      threeinRoom: 0,
      twoinRoom: 1200,
      oneinRoom: 2400,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["na", "na1", "na2"],
    ),
    ApartmentModel(
      name: "Vicious",
      price: '~2000',
      location: "Kwaprow",
      telephone: '0249962878',
      desc: "Located around sandwich lecture theatre",
      threeinRoom: 0,
      twoinRoom: 2000,
      oneinRoom: 4000,
      features: ["Kitchen", "Toilet", "Wardrobe", "Bathroom"],
      images: ["vicious", "vicious1", "vicious"],
    ),
  ];
}
